export const USER_ID = 'USER_ID';
export const USER_SET = 'USER_SET';
export const AUTHENTICATE = 'AUTHENTICATE';
export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const USER_REQUEST = 'USER_REQUEST';
export const CURRENT_USER = 'USER_CURRENT';

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_EXISTING = 'LOGIN_EXISTING';
export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACTION_CLEAR_PROFILE = 'ACTION_CLEAR_PROFILE';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';

export const USER_AVATAR = 'USER_AVATAR';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';

export const USER_FIND = 'USER_FIND';
export const USER_DELETE = 'USER_DELETE';

export const GET_USER_SETTINGS = 'GET_USER_SETTINGS';

export const SET_CHANNEL_EDIT = 'SET_CHANNEL_EDIT';
export const SET_USER_EDIT = 'SET_USER_EDIT';
export const SET_PROFILE_EDIT = 'SET_PROFILE_EDIT';

export const PROFILE_UPDATE_ALL = 'PROFILE_UPDATE_ALL';
export const USER_UPDATE_ALL = 'USER_UPDATE_ALL';
export const GENERAL_UPDATE = 'GENERAL_UPDATE';

export const CHANNEL_USER_CREATE = 'CHANNEL_USER_CREATE';

export const USER_FIND_BY_ID = 'USER_FIND_BY_ID';
export const USER_REPLACE_BY_ID = 'USER_REPLACE_BY_ID';
export const USER_UPDATE_BY_ID = 'USER_UPDATE_BY_ID';
export const USER_DELETE_BY_ID = 'USER_DELETE_BY_ID';
