export const EVENT_WAYBILL = 'EVENT_WAYBILL';
export const WAYBILL_REQUEST = 'WAYBILL_REQUEST';
export const WAYBILL_CATEGORY = 'WAYBILL_CATEGORY';

export const WAYBILL_REQUESTING = 'WAYBILL_REQUESTING';
export const WAYBILL_SUCCESS = 'WAYBILL_SUCCESS';
export const WAYBILL_ERROR = 'WAYBILL_ERROR';
export const WAYBILL_EXISTING = 'WAYBILL_EXISTING';
